/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

ANSWER : 4613732
*/

#include <iostream>
#include <stdint.h>

int main()
{
   uint64_t fib1 = 2;
   uint64_t fib2 = 3;
   uint64_t buff;

   uint64_t sum = 0;

   while(fib1 < 4000000)
   {
      if((fib1 % 2) == 0)
      {
         sum += fib1;
      }

      buff = fib2;
      fib2 += fib1;
      fib1 = buff;
   }
   
   std::cout << "ans : " << sum << '\n';
   std::cin.get();
   return 0;
}
